# Generated by Django 5.1 on 2024-08-22 03:16

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalResident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10000, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=10000)),
                ('age', models.CharField(blank=True, max_length=10000, null=True)),
                ('species', models.CharField(blank=True, max_length=10000, null=True)),
                ('story', ckeditor_uploader.fields.RichTextUploadingField()),
                ('event_suitability', models.CharField(blank=True, choices=[('All ages', 'All ages'), ('7+ ages', '7+ ages'), ('Not suitable', 'Not suitable')], default='All ages', max_length=10000, null=True)),
                ('animal_picture', models.ImageField(upload_to='animal_residents/')),
            ],
        ),
        migrations.CreateModel(
            name='BookAnEncounterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('email', models.CharField(max_length=10000)),
                ('phone_number', models.CharField(max_length=10000)),
                ('event_description', models.TextField()),
                ('preferred_date_of_event', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='DragonShelterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DragonShelterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.URLField(blank=True, max_length=10000, null=True)),
                ('instagram_username', models.CharField(blank=True, max_length=10000, null=True)),
                ('twitter_username', models.CharField(blank=True, max_length=10000, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=10000, null=True)),
                ('booking_enquiries_email', models.CharField(blank=True, max_length=10000, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10000, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=10000, null=True)),
                ('about', ckeditor_uploader.fields.RichTextUploadingField()),
                ('short_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaddyPony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10000, null=True)),
                ('age', models.CharField(blank=True, max_length=10000, null=True)),
                ('species', models.CharField(blank=True, max_length=10000, null=True)),
                ('story', ckeditor_uploader.fields.RichTextUploadingField()),
                ('event_suitability', models.CharField(blank=True, choices=[('All ages', 'All ages'), ('7+ ages', '7+ ages'), ('Not suitable', 'Not suitable')], default='All ages', max_length=10000, null=True)),
                ('pony_profile_picture', models.ImageField(upload_to='animal_residents/paddy_pony')),
            ],
        ),
    ]
